# -*- coding: utf-8 -*-
"""crop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVpG_a9QXMQj90Wz1vrSB0eDgz2ZU1DZ
"""

# Install necessary libraries
!pip install pandas numpy scikit-learn matplotlib seaborn joblib

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib  # To save/load the model

from google.colab import files
uploaded = files.upload()

import zipfile
import io

# Check the keys in the uploaded dictionary to confirm the filename
# print(uploaded.keys())

# The uploaded file is a zip archive, extract the CSV
# zip_file = zipfile.ZipFile(io.BytesIO(uploaded['archive.zip']), 'r')

# Assuming the CSV file inside the zip is named 'Crop_recommendation.csv'
# Update this if the file name inside the zip is different
csv_filename = 'Crop_recommendation.csv'

# Extract the CSV file from the zip archive
# with zip_file.open(csv_filename) as csv_file:
#     df = pd.read_csv(csv_file)

# Read the CSV file directly from the uploaded dictionary
df = pd.read_csv(io.BytesIO(uploaded[csv_filename]))

# Display first few rows
df.head()

# Basic info about the dataset
df.info()

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

# Statistical summary of the dataset
df.describe()

# Correlation matrix (excluding the target label 'label')
plt.figure(figsize=(8, 6))
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap="YlGnBu")
plt.title("Feature Correlation Heatmap")
plt.show()

# Plot distribution of crops (target variable 'label')
plt.figure(figsize=(12, 6))
sns.countplot(y='label', data=df, order=df['label'].value_counts().index)
plt.title("Crop Distribution")
plt.show()

# Split features and labels
X = df.drop('label', axis=1)
y = df['label']

# Split the data into training and test sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model's performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Save the trained model to a file
joblib.dump(model, 'crop_recommendation_model.pkl')

# Example input: [N, P, K, temperature, humidity, ph, rainfall]
sample_input = np.array([[90, 42, 43, 20.5, 82, 6.5, 200]])  # Example values
predicted_crop = model.predict(sample_input)

# Output the recommended crop based on the given conditions
print(f"Recommended Crop for given conditions: {predicted_crop[0]}")

# Load the saved model (if needed)
crop_model = joblib.load('crop_recommendation_model.pkl')

# Example: Use the loaded model to make predictions
sample_input = np.array([[90, 42, 43, 20.5, 82, 6.5, 200]])  # Example values
predicted_crop = crop_model.predict(sample_input)

# Output the recommended crop based on the given conditions
print(f"Recommended Crop for given conditions: {predicted_crop[0]}")

# Download the saved model to your local machine
files.download('crop_recommendation_model.pkl')