# -*- coding: utf-8 -*-
"""main_Sat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152RemrFnVBn-PCvaS_3hV5WJwVdOHjyy
"""

# -*- coding: utf-8 -*-
# Satellite NDVI Processing Script

#!pip install pystac-client stackstac xarray dask geopandas folium geemap planetary-computer --quiet

from pystac_client import Client
import planetary_computer
import stackstac
import xarray as xr
import joblib
import matplotlib.pyplot as plt

# Connect to Planetary Computer STAC catalog
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

# Define area of interest
bbox = [78.0, 20.0, 79.0, 21.0]  # Example region (India)
datetime = "2025-01-01/2025-01-10"

# Search for Sentinel-2 L2A images with low cloud cover
search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime=datetime,
    query={"eo:cloud_cover": {"lt": 10}}
)

items = list(search.get_items())
print(f"Images found: {len(items)}")

if len(items) == 0:
    raise ValueError("No Sentinel-2 images found for the given area/time range.")

# ✅ Sign items to authorize asset access
signed_items = [planetary_computer.sign(item) for item in items]

# Stack Red (B04) and NIR (B08) bands
ds = stackstac.stack(
    signed_items,
    assets=["B04", "B08"],
    bounds_latlon=bbox,
    epsg=4326,
    resolution=0.00025
)

# Convert to dataset and extract bands
ds = ds.to_dataset("band")
red = ds["B04"]
nir = ds["B08"]

# Compute NDVI
ndvi = (nir - red) / (nir + red)
ndvi_median = ndvi.median(dim="time")

print("✅ NDVI computed successfully!")

# Visualize NDVI
ndvi_median.plot(cmap="YlGn")
plt.title("NDVI Median (Jan 2025)")
plt.show()

# Save and download NDVI
# Drop 'proj:shape' and 'spatial_ref' variables before saving to NetCDF
ndvi_median = ndvi_median.drop_vars(['proj:shape', 'spatial_ref'], errors='ignore')
ndvi_median.to_netcdf("ndvi_output.nc")
print("✅ NDVI dataset saved as 'ndvi_output.nc'")

from google.colab import files
files.download("ndvi_output.nc")