# -*- coding: utf-8 -*-
"""satellite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o35yyPnckJ96-jrfR51I26wS8EEFY1I5
"""

# Install necessary libraries for accessing and processing Sentinel-2 data
!pip install pystac-client stackstac xarray dask geopandas folium geemap --quiet

# Import libraries
from pystac_client import Client
import stackstac
import xarray as xr
import joblib
import matplotlib.pyplot as plt

# Initialize the STAC catalog from Microsoft Planetary Computer
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

# Define your area of interest (bounding box: [min lon, min lat, max lon, max lat])
bbox = [78.0, 20.0, 79.0, 21.0]  # Example: small area in India

# Set the time range (e.g., January 2025)
datetime = "2025-01-01/2025-01-10"  # Adjust according to your needs

# Search for Sentinel-2 images with <10% cloud cover
search = catalog.search(
    collections=["sentinel-2-l2a"],  # Use Sentinel-2 Level 2A data
    bbox=bbox,  # Bounding box (area of interest)
    datetime=datetime,  # Time range for the data
    query={"eo:cloud_cover": {"lt": 10}}  # Filter cloud cover to be less than 10%
)

# Get the items (images)
items = list(search.get_items())  # Convert generator to list
print(f"Images found: {len(items)}")  # Check how many images were found

# Stack the Sentinel-2 bands (e.g., B04 for Red and B08 for NIR) into an xarray dataset
ds = stackstac.stack(
    items,  # List of items (Sentinel-2 images)
    assets=["B04", "B08"],  # Select Red (B04) and NIR (B08) bands
    bounds_latlon=bbox,  # Set bounds for the area of interest
    epsg=4326,  # WGS84 Coordinate Reference System
    resolution=0.00025  # Set resolution (change as needed)
)

# Print the dimensions of the dataset to inspect them
print("Dataset dimensions before renaming:")
print(ds.dims)

# Convert to xarray dataset and fix the band dimension
# Check the output of ds.dims to determine the correct dimension name to rename
# ds = ds.rename({"band_name": "band"}) # Assuming 'band_name' is the correct dimension name based on typical stackstac output
ds = ds.to_dataset("band")  # Convert to xarray dataset with 'band' dimension

# Select the Red and NIR bands
red = ds["B04"]  # Band 04: Red
nir = ds["B08"]  # Band 08: NIR

# Compute NDVI (NDVI = (NIR - Red) / (NIR + Red))
ndvi = (nir - red) / (nir + red)

# Calculate the median NDVI over time (if you have multiple images)
ndvi_median = ndvi.median(dim="time")  # median across the time dimension (optional)

print("✅ NDVI computed successfully!")

# Save the NDVI dataset as a .pkl file using joblib
joblib.dump(ndvi_median, 'ndvi_output.pkl')
print("✅ NDVI dataset saved as 'ndvi_output.pkl'")

from google.colab import files
files.download('ndvi_output.pkl')

"""
# Ensure that 'ndvi_median' is a NumPy array and in a proper format for plotting
ndvi_median_values = ndvi_median.values  # Extract NumPy array from xarray DataArray

# Check if it's a 2D array
print(f"NDVI Median Shape: {ndvi_median_values.shape}")

# Plot the NDVI median
plt.imshow(ndvi_median_values, cmap="RdYlGn")  # Using a color map
plt.colorbar(label="NDVI")  # Add a colorbar to the plot
plt.title("NDVI Map")
plt.show()  # Display the plot
"""