# -*- coding: utf-8 -*-
"""croprec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRp3A2D-bwsJ2LXmENKgUb5tDS2i0CBu
"""

# Step 1: Install & Import Dependencies
!pip install pandas numpy scikit-learn matplotlib seaborn

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
import zipfile

# Replace filename if it's slightly different
# Check the keys in the uploaded dictionary to confirm the filename
# print(uploaded.keys())

# The uploaded file is a zip archive, extract the CSV
zip_file = zipfile.ZipFile(io.BytesIO(uploaded['archive.zip']), 'r')

# Assuming the CSV file inside the zip is named 'Crop_recommendation.csv'
# You might need to check the actual filename inside the zip if it's different
csv_filename = 'Crop_recommendation.csv'

# Extract the CSV file from the zip archive
with zip_file.open(csv_filename) as csv_file:
    df = pd.read_csv(csv_file)

df.head()

# Basic info
df.info()

# Check missing values
print("\nMissing values:\n", df.isnull().sum())

# Statistical summary
df.describe()

# Correlation matrix
plt.figure(figsize=(8,6))
# Exclude the 'label' column as it's not numeric
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap="YlGnBu")
plt.title("Feature Correlation Heatmap")
plt.show()

plt.figure(figsize=(12,6))
sns.countplot(y='label', data=df, order=df['label'].value_counts().index)
plt.title("Crop Distribution")
plt.show()

# Split features and labels
X = df.drop('label', axis=1)
y = df['label']

# Split into training and testing sets (80-20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Evaluate model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Example input: [N, P, K, temperature, humidity, ph, rainfall]
sample_input = np.array([[90, 42, 43, 20.5, 82, 6.5, 200]])  # example values
predicted_crop = model.predict(sample_input)

print(f"Recommended Crop for given conditions: {predicted_crop[0]}")