# This code was developed and executed in a Google Colab environment.

# -*- coding: utf-8 -*-
"""crop1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjsM7omyAT3SXhcBEUcGFZpzrhAzSJV2
"""

# -*- coding: utf-8 -*-
"""crop_recommendation"""

# Install necessary libraries
!pip install pandas numpy scikit-learn matplotlib seaborn joblib

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
from google.colab import files
import io

# Upload dataset
uploaded = files.upload()

# CSV filename is 'Crop_recommendation.csv'
csv_filename = 'Crop_recommendation.csv'
df = pd.read_csv(io.BytesIO(uploaded[csv_filename]))

# Displaying basic info
print(df.head())
print(df.info())
print("\nMissing values:\n", df.isnull().sum())

# Visualizing correlations
plt.figure(figsize=(8, 6))
sns.heatmap(df.drop('label', axis=1).corr(), annot=True, cmap="YlGnBu")
plt.title("Feature Correlation Heatmap")
plt.show()

# Visualizing crop distribution
plt.figure(figsize=(12, 6))
sns.countplot(y='label', data=df, order=df['label'].value_counts().index)
plt.title("Crop Distribution")
plt.show()

# Split features and target
X = df.drop('label', axis=1)
y = df['label']

# Split into training and test sets (80-20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize RandomForest with class_weight='balanced' to handle imbalance
model = RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

# Evaluate model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion matrix
plt.figure(figsize=(12, 8))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap="YlGnBu",
            xticklabels=df['label'].unique(), yticklabels=df['label'].unique())
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Saving the trained model
joblib.dump(model, 'crop_recommendation_model.pkl')

# Function to predict crop for new inputs
def recommend_crop(input_features):
    """
    input_features: list of [N, P, K, temperature, humidity, ph, rainfall]
    """
    input_array = np.array([input_features])

    # Check if values are within reasonable ranges
    df_stats = X.describe()
    for i, col in enumerate(X.columns):
        min_val = df_stats[col]['min']
        max_val = df_stats[col]['max']
        if input_features[i] < min_val or input_features[i] > max_val:
            print(f"Warning: {col} value {input_features[i]} is outside training range ({min_val}-{max_val})")

    predicted_crop = model.predict(input_array)
    return predicted_crop[0]

# Example usage
sample_input = [90, 42, 43, 20.5, 82, 6.5, 200]
print(f"Recommended Crop: {recommend_crop(sample_input)}")

# Download model
files.download('crop_recommendation_model.pkl')