# -*- coding: utf-8 -*-
"""python projects

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUz5dCTIOZ-doPpMaZmdtxX5O20FERTg
"""

# HarvestIQ
#import dataset
from google.colab import files
files.upload()                           # Upload your kaggle.json file

#Set it up
!mkdir -p ~/.kaggle                      #create directory
!cp kaggle.json ~/.kaggle/               #copy file to directory
!chmod 600 ~/.kaggle/kaggle.json         #set read write permissions to owner only

#Download dataset
!kaggle datasets download -d emmarex/plantdisease

#Unzip
!unzip plantdisease.zip -d plantdisease

#check folder structure
import os
os.listdir("plantdisease/PlantVillage")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

import keras

from  tensorflow.keras.preprocessing.image import ImageDataGenerator , img_to_array , load_img
from keras.applications.vgg19 import VGG19 , preprocess_input , decode_predictions

#EDA exploratory data analysis
len(os.listdir("plantdisease/PlantVillage"))

#Prepare images by applying random transformations
train_datagen = ImageDataGenerator(zoom_range= 0.5, shear_range= 0.3, horizontal_flip=True, preprocessing_function= preprocess_input)
val_datagen = ImageDataGenerator(preprocessing_function= preprocess_input)

#loads images from the folder and prepare them
train = train_datagen.flow_from_directory(directory="plantdisease/PlantVillage", target_size=(256,256), batch_size=32)
val = val_datagen.flow_from_directory(directory="plantdisease/PlantVillage", target_size=(256,256), batch_size=32)

#batches of image and labels
t_img, label = next(train)

t_img.shape

def plotImage(img_arr, label):
  for im , l in zip(img_arr, label):
    plt.figure(figsize=(5,5))
    plt.imshow(im)
    plt.show()

plotImage(t_img[:3],label[:3])

from keras.layers import Dense, Flatten
from keras.models import Model

#VGG19: A pre-trained image classification model
base_model = VGG19(input_shape=(256,256,3), include_top= False)
#include_top=False means it doesn't include the final classification layer (we will add our own).

#we don't want to train those layers, just use them as feature extractors.
for layer in base_model.layers:
  layer.trainable = False

base_model.summary()

X = Flatten()(base_model.output)

X = Dense(units= 15, activation= 'softmax')(X)

#create model
model = Model(base_model.input, X)

model.compile(optimizer= 'adam' , loss= keras.losses.categorical_crossentropy , metrics= ['accuracy'])

from keras.callbacks import ModelCheckpoint, EarlyStopping

#early stopping
es= EarlyStopping(monitor= 'val_accuracy', min_delta= 0.01, patience= 3, verbose= 1)

#model check point
mc = ModelCheckpoint(filepath= "best_plant_disease_model.h5", monitor= 'val_accuracy', verbose= 1, save_best_only= True)

cb = [es, mc]

total_no_of_images = len(train.filenames) # train.batch_size
print(total_no_of_images)
print(train.batch_size)
steps_per_epoch = np.ceil(total_no_of_images/train.batch_size)
print(total_no_of_images/train.batch_size)
print(steps_per_epoch)

#This trains the model with the training data and validates it with the validation data
his = model.fit(train, steps_per_epoch= int(steps_per_epoch), epochs= 50, verbose= 1, callbacks= cb, validation_data= val, validation_steps= int(steps_per_epoch))

h = his.history
h.keys()

plt.plot(h['accuracy'])
plt.plot(h['val_accuracy'] , c = "red")
plt.title("acc vs v-acc")
plt.show()

#load best model

from keras.models import load_model

model = load_model("/content/best_plant_disease_model.h5")

acc = model.evaluate(val)[1]

print(f"The accuracy of your model is {acc*100} %")

ref = dict(zip(list(train.class_indices.values()) , list(train.class_indices.keys())))

print(ref)

#This function takes the path of an image, preprocesses it, and predicts which class (disease) the image belongs to.
def prediction(path):

  img = load_img(path , target_size= (256,256))

  i = img_to_array(img)

  im = preprocess_input(i)

  img = np.expand_dims(im, axis= 0)

  #print(img.shape)

  pred = np.argmax(model.predict(img))

  print(f" the image belogs to  { ref[pred] }")

#path to a file within the unzipped dataset
path = "plantdisease/PlantVillage/Tomato__Target_Spot/0abb0bf0-8a1e-4699-80ee-c434385d9514___Com.G_TgS_FL 8115.JPG"

prediction(path)

# Download model to your PC
from google.colab import files
files.download("best_plant_disease_model.h5")