# -*- coding: utf-8 -*-
"""satellite1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gu8JeeO3PGW2jaPRzujLbSnLp26r1opU
"""

import ee
import geemap

# Step 1: Authenticate your account (only once per session)
ee.Authenticate()

# Step 2: Initialize the Earth Engine API
# Replace "YOUR_PROJECT_ID" with your actual Google Cloud Project ID
ee.Initialize()

print("✅ Google Earth Engine initialized successfully!")

!pip install pystac-client stackstac xarray --quiet
from pystac_client import Client
import stackstac

# Access Sentinel-2 data (no login needed)
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=[78, 20, 79, 21],
    datetime="2025-01-01/2025-01-10"
)

items = list(search.get_items())
print("Images found:", len(items))

!pip install pystac-client stackstac xarray dask geopandas folium geemap --quiet

from pystac_client import Client
import stackstac, xarray as xr
import geemap.foliumap as geemap

# Define an area of interest (longitude/latitude box)
bbox = [78, 20, 79, 21]   # e.g. central India
time_range = "2025-01-01/2025-01-31"

catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime=time_range,
    query={"eo:cloud_cover": {"lt": 20}}
)

items = list(search.get_items())
print("Images found:", len(items))

import stackstac
import xarray as xr
from pystac_client import Client

# -----------------------------
# 1️⃣ Define your bounding box
# -----------------------------
latitude = 20.5937
longitude = 78.9629
bbox_size = 0.05  # half-size of bounding box in degrees

bbox = [
    longitude - bbox_size, latitude - bbox_size,
    longitude + bbox_size, latitude + bbox_size
]

# -----------------------------
# 2️⃣ Search for Sentinel-2 images in MPC
# -----------------------------
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")
search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime="2025-01-01/2025-01-31",
    query={"eo:cloud_cover": {"lt": 20}}
)
items = list(search.items())

print(f"Images found: {len(items)}")
if len(items) == 0:
    raise ValueError("No images found for this location and date range!")

# -----------------------------
# 3️⃣ Stack images with Stackstac
# -----------------------------
ds = stackstac.stack(
    items,
    assets=["B04", "B08"],  # Red and NIR bands
    bounds_latlon=bbox,
    epsg=4326,               # fix CRS issue
    resolution=0.00025
)

# Fix band dimension if needed
band_dim = "variable" if "variable" in ds.dims else "band"
ds = ds.rename({band_dim: "band"}) if band_dim != "band" else ds

# Convert to xarray dataset
ds = ds.to_dataset("band")

# -----------------------------
# 4️⃣ Compute NDVI
# -----------------------------
red = ds["B04"]
nir = ds["B08"]

ndvi = (nir - red) / (nir + red)
ndvi_median = ndvi.median(dim="time")  # median over time if multiple images

print("✅ NDVI computed successfully!")

from pystac_client import Client
import stackstac

# Connect to MPC STAC catalog
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

# Define your area of interest (AOI) as a bounding box: [min_lon, min_lat, max_lon, max_lat]
bbox = [78.0, 20.0, 79.0, 21.0]  # Example: small area in India

# Search Sentinel-2 surface reflectance images
search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime="2025-01-01/2025-01-10",
    query={"eo:cloud_cover": {"lt": 10}}  # Filter clouds <10%
)

items = list(search.get_items())
print(f"Images found: {len(items)}")

import stackstac

# Example: use WGS84 (EPSG:4326)
ds = stackstac.stack(
    items,
    assets=["B04", "B08"],
    bounds_latlon=bbox,
    epsg=4326,       # enforce common CRS
    resolution=10,   # Sentinel-2 resolution in meters
    chunksize=4096   # optional, helps with memory
)
ds = ds.to_dataset("band")

# Define bounding box (min longitude, min latitude, max longitude, max latitude)
lon_min, lat_min = 78.95, 20.58   # southwest corner
lon_max, lat_max = 79.05, 20.63   # northeast corner

from pystac_client import Client

search = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1").search(
    collections=["sentinel-2-l2a"],
    datetime="2025-01-01/2025-01-05",
    bbox=[lon_min, lat_min, lon_max, lat_max],
    limit=5  # fetch only 5 items
)

items = list(search.items())
print(f"Number of items fetched: {len(items)}")

from pystac_client import Client
import stackstac
import xarray as xr

# 1️⃣ Connect to MPC STAC
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

# 2️⃣ Define your area of interest (bounding box: [min lon, min lat, max lon, max lat])
bbox = [78.5, 20.5, 79.5, 21.0]  # example: part of India

# 3️⃣ Search for Sentinel-2 L2A images in that area
search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime="2025-01-01/2025-01-05",
    query={"eo:cloud_cover": {"lt": 10}}  # <10% cloud
)

items = list(search.get_items())  # convert generator to list
print("Number of items found:", len(items))

# 4️⃣ Stack the bands into an xarray Dataset
ds = stackstac.stack(
    items,
    assets=["B04", "B08"],  # Red and NIR
    bounds_latlon=bbox
)

# 5️⃣ Select bands
red = ds.sel(band="B04")
nir = ds.sel(band="B08")

# 6️⃣ Compute NDVI
ndvi = (nir - red) / (nir + red)

print("NDVI dataset ready:", ndvi)

items = list(search.get_items())[:2]  # only take the first 2 images

# 4️⃣ Stack the bands into an xarray Dataset
ds = stackstac.stack(
    items,
    assets=["B04", "B08"],  # Red and NIR bands
    bounds_latlon=bbox,
    epsg=32644
)

# 5️⃣ Select bands
red = ds.sel(band="B04")
nir = ds.sel(band="B08")

# 6️⃣ Compute NDVI
ndvi = (nir - red) / (nir + red)

print("NDVI dataset ready:", ndvi)

import warnings
import stackstac

safe_items = []

for item in items:
    try:
        # Try opening this image to see if it works
        _ = stackstac.stack([item], assets=["B04", "B08"], bounds_latlon=bbox, epsg=32644)
        safe_items.append(item)  # add only if successful
    except Exception as e:
        warnings.warn(f"Skipping image due to error: {e}")

# Now stack only the safe images
ds = stackstac.stack(safe_items, assets=["B04", "B08"], bounds_latlon=bbox, epsg=32644)

datetime="2025-06-01/2025-06-05"  # early June 2025

# Only take the first 2 images to be safe
items = list(search.get_items())[:2]
print("Number of items found:", len(items))

# Stack the bands into an xarray Dataset
ds = stackstac.stack(
    items,
    assets=["B04", "B08"],  # Red and NIR bands
    bounds_latlon=bbox,
    epsg=32644
)

# Select bands
red = ds.sel(band="B04")
nir = ds.sel(band="B08")

# Compute NDVI
ndvi = (nir - red) / (nir + red)
print("NDVI dataset ready:", ndvi)

plt.savefig(f"NDVI_{str(t)[:10]}.png")

search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=bbox,
    datetime="2025-06-01/2025-06-05",  # early June
    query={"eo:cloud_cover": {"lt": 10}}
)

items = list(search.get_items())[:2]
print("Number of items found:", len(items))

ds = stackstac.stack(
    items,
    assets=["B04", "B08"],  # Red and NIR bands
    bounds_latlon=bbox,
    epsg=32644
)

red = ds.sel(band="B04")
nir = ds.sel(band="B08")

ndvi = (nir - red) / (nir + red)
print("NDVI dataset ready:", ndvi)

# Save NDVI dataset as .pkl
import joblib
joblib.dump(ndvi, 'ndvi_output.pkl')
print("✅ NDVI dataset saved as 'ndvi_output.pkl'")
